### ISSUE TITLE
PHP Parse error:  syntax error, Composer/IO/BaseIO.php on line 163

### ISSUE THREAD

**Issue by shodanx2** [ShaneMcC/PXE-Manager#156]
Hello,
I'm giving this a try in an LXC container running ubuntu 22.04 headless

I mostly followed the instructions during install, skipped the firewall stuff as my network config is not passthrough (using dhcp proxy in the same broadcast as my "real"  dhcp server) and I also used different settings for dnsmasq

I get a problem when I make it to "composer install", fails with the following error

"PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /usr/share/php/Composer/IO/BaseIO.php on line 163"

Did some initial search found

This [video](https://www.youtube.com/watch?v=O2yiV_LFJxU), which claims it's a php version error

And this [other issue](https://github.com/Seldaek/monolog/issues/1597), which also suggests it's a php version and maybe use --ignore-platform-reqs

php version reports

root@pxemanager:/var/www/pxe-manager# php --version
PHP 7.4.30 (cli) (built: Aug  1 2022 15:06:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies

Since the installation instruction call  libapache2-mod-php7.4 git php7.4-sqlite3 by version number, I imagine there's something significant about php 7.4 ?

I tried running composer install --ignore-platform-reqs
This did not change the error message

I'm not sure what to try next, I'll try upgrade or downgrading php maybe 

I've noticed these lines, maybe adding the ppa:ondrej/apache2 repository and running upgrade will do something

CAVEATS:
1. If you are using php-gearman, you need to add ppa:ondrej/pkg-gearman
2. If you are using apache2, you are advised to add ppa:ondrej/apache2
3. If you are using nginx, you are advised to add ppa:ondrej/nginx-mainline
   or ppa:ondrej/nginx

PLEASE READ: If you like my work and want to give me a little motivation, please                                                                  consider donating regularly: https://donate.sury.org/

**Comment by shodanx2** [comment]
Ok, just gave a try increasing php version to 8.1

```
root@pxemanager:/var/www/pxe-manager# composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]?
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 9 installs, 0 updates, 0 removals
  - Downloading bramus/router (dev-master 40105ae)
  - Downloading psr/log (1.1.4)
  - Downloading filp/whoops (2.14.5)
  - Downloading shanemcc/php-db (0.5)
  - Downloading symfony/polyfill-php80 (v1.25.0)
  - Downloading symfony/polyfill-mbstring (v1.25.0)
  - Downloading symfony/var-dumper (v5.4.8)
  - Downloading symfony/polyfill-ctype (v1.25.0)
  - Downloading twig/twig (v3.4.1)
  - Installing bramus/router (dev-master 40105ae): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing filp/whoops (2.14.5): Extracting archive
  - Installing shanemcc/php-db (0.5): Extracting archive
  - Installing symfony/polyfill-php80 (v1.25.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.25.0): Extracting archive
  - Installing symfony/var-dumper (v5.4.8): Extracting archive
  - Installing symfony/polyfill-ctype (v1.25.0): Extracting archive
  - Installing twig/twig (v3.4.1): Extracting archive
Generating autoload files
6 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
root@pxemanager:/var/www/pxe-manager# php /var/www/pxe-manager/admin/init.php
PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/pxe-manager/functions.php:15
Stack trace:
#0 /var/www/pxe-manager/functions.php(15): PDO->__construct()
#1 /var/www/pxe-manager/admin/init.php(3): require_once('...')
#2 {main}
  thrown in /var/www/pxe-manager/functions.php on line 15

```

Made it one step further, according to [this post](https://stackoverflow.com/questions/2852748/pdoexception-could-not-find-driver), I might be missnig the PDO SQL driver

I just ran apt install php8.1 to install it, I didn't try to purge php7.* / autoclean / autoremove yet 

Having a look at my list of installed packages
![image](https://user-images.githubusercontent.com/10621885/187358518-7c4b0da8-3151-4b26-a731-5070d7a32cf3.png)

Looks like the only php7 module I'm missing is sqlite3, makes sense, PDO is sql related, ok let's try that 

apt install php8.1-sqlite3

````
root@pxemanager:/var/www/pxe-manager# php /var/www/pxe-manager/admin/init.php
dataVersion Current Version: 0
dataVersion Updating to version 1: success
dataVersion Updating to version 2: success
dataVersion Updating to version 3: success
dataVersion Updating to version 4: success
dataVersion Updating to version 5: success
dataVersion Updating to version 6: success
dataVersion Updating to version 7: success
root@pxemanager:/var/www/pxe-manager#

````

Oh yes !

Ok almost there

![image](https://user-images.githubusercontent.com/10621885/187359361-06d62b5d-adbe-4f1f-8c69-8b3f6acd5543.png)

Blank page, but I'm getting there ...

**Comment by shodanx2** [comment]
tail /var/log/apache2/* -f

Uncaught RuntimeException: Unable to create the cache directory (/var/www/pxe-manager/templates_c/5b).

Looks like it's an access control issue of some kind

![image](https://user-images.githubusercontent.com/10621885/187359988-3dc34a04-e03c-45ac-a3f4-0fd347815555.png)

Let's reset everything

`chown -Rfv www-data: /var/www/pxe-manager/`

and yep, that did it 

![image](https://user-images.githubusercontent.com/10621885/187360355-dee16be8-68e4-4b87-9f0e-808381c7eafb.png)

Ok, time to play with this thing !

**Comment by ShaneMcC** [comment]
Thanks for the detailed bug report/fixing steps.

The install instructions for 7.4 were to ensure it was a newer version of PHP than the default. Should work perfectly fine on 8.1.

I'll thought I'd updated the docs for 20.04, seems not. I'll give them a pass over for 22.04.
